# fly.toml app configuration file generated for prod-dt-21-8-24-3-1724241827-client on 2024-08-21T12:04:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prod-dt-21-8-24-3-1724241827-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
